### ISSUE TITLE
Add maximize window size to Desktop UI & add Settings to WebUI

### ISSUE THREAD

**Issue by AKDigitalAgency** [rupeshs/fastsdcpu#69]
Add maximize size window option or make it by defult full screen other wise it's PIA to use inside tiny box :(
Cant even read tine text  see attachment images!
Add in WebUI ability to choose models and Loras like you have in Desktop UI settings!

![Screenshot 2023-11-17 135632](https://github.com/rupeshs/fastsdcpu/assets/147016521/a91d5f5c-a63c-449f-b72b-42ed64445240)
![Screenshot 2023-11-17 135649](https://github.com/rupeshs/fastsdcpu/assets/147016521/bd1596a5-ad5c-4c08-821e-123230efceff)
![Screenshot 2023-11-17 142712](https://github.com/rupeshs/fastsdcpu/assets/147016521/514b10ac-dbb7-46e0-b8ca-1218a3be58e7)

**Comment by rupeshs** [comment]
@AKDigitalAgency  I have fixed that issue in the latest master, do a git pull (no need to pip install, there is no package change). It will be included in the next release.

**Comment by AKDigitalAgency** [comment]
Update is better but still doesnt fit screen attached image can see bottom of DesktopUI is hidden by taskbar  :(
Please make it default max size full screen!
Please add progress bar to desktop UI & negative prompt box to WebUI
Also, it keeps freezing up or crushing on 2nd image generation :(
As you can see from image 1st was image was generated in 8min while 2nd image was frozen and showed being stuck on ETA of 2hr 30min before it crushed :((

![Screenshot 2023-11-17 142712](https://github.com/rupeshs/fastsdcpu/assets/147016521/8973121f-7024-4c07-923e-a3183002491a)
![Screenshot 2023-11-18 133215](https://github.com/rupeshs/fastsdcpu/assets/147016521/72467924-cbf5-43bf-b9e6-dae9cdba0289)
